databases:
  - name: distributed-peer-review
    databaseName: distributed-peer-review
    user: distributed_peer_review_user

services:
  - type: web
    name: distributed-peer-review
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn peergrade.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: distributed-peer-review
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
